/* ..:: Ejecutar con un usuario con privilegio SYS ::.. */

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER USER_WORK IDENTIFIED BY user123;

GRANT CONNECT TO USER_WORK;

GRANT ALL PRIVILEGES TO USER_WORK;

GRANT EXECUTE ANY PROCEDURE TO USER_WORK;

GRANT UNLIMITED TABLESPACE TO USER_WORK;