/* ..:: Ejecutar con un usuario con privilegio SYS ::.. */

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER ADA_USER IDENTIFIED BY user123;

GRANT CONNECT TO ADA_USER;

GRANT ALL PRIVILEGES TO ADA_USER;

GRANT EXECUTE ANY PROCEDURE TO ADA_USER;

GRANT UNLIMITED TABLESPACE TO ADA_USER;